In [1]:
import pandas as pd

## Load detail levels

In [3]:
from matmat.core.detail_level import core as dl, factory as dl_factory

In [4]:
dls = dl_factory.make_dl_dict_from_path(path="../../data/4-PlaneFR/1-accounts/Exiobase/3.10.2_pxp_2019", file_name="detail_levels.xlsx")

In [5]:
regions = dls["regions"]
sectors = dls["sectors"]
final_demand_categories = dls["final_demand_categories"]

## Build a system

In [6]:
from matmat.core.accounts.system import builder as system_builder
system_director = system_builder.get_director(reset=True)

In [7]:
system_director.set_regions(regions)
system_director.set_sectors(sectors)
system_director.set_final_demand_categories(final_demand_categories)

In [8]:
system = system_director.make_exo_invest_matrix_system()

In [9]:
system.id.base_year = 2019

## Build an extension

In [15]:
from matmat.core.accounts.extension import builder as extension_builder
extension_director = extension_builder.get_director(reset=True)

In [16]:
extension_director.set_regions(regions)
extension_director.set_sectors(sectors)
extension_director.set_final_demand_categories(final_demand_categories)

### Build an extension categories detail level

In [ ]:
ghg_emissions_df = pd.DataFrame({"perimeter": ["combustion", "other"]})

In [ ]:
ghg_emissions_df

In [ ]:
ghg_emissions_dl = dl.ExtensionCategoriesDL(extension_name="ghg_emissions", df=ghg_emissions_df)

In [ ]:
ghg_emissions_dl.df

### Use the detail level to build an extension

In [ ]:
extension_director.set_extension_categories(ghg_emissions_dl)

In [ ]:
ghg_emissions = extension_director.make_use_based_extension(name="ghg_emissions")

In [ ]:
ghg_emissions.F_Y.df

## Build an accounts from a system and an extension

In [10]:
from matmat.core.accounts import builder as accounts_builder
accounts_director = accounts_builder.get_director(reset=True)

In [14]:
accounts = accounts_director.make_from_system_and_extensions(
    system=system,
    extensions={water.name: water}
)

NameError: name 'water' is not defined

## Load an accounts, add an extension

In [28]:
accounts_3_10 = accounts_director.make_from_path("../../data/4-PlaneFR/1-accounts/Exiobase/3.10.2_pxp_2019", extensions_names=["water"])

In [23]:
accounts_3_9 = accounts_director.make_from_path("../../data/4-PlaneFR/1-accounts/Exiobase/3.9.6_pxp_2019", extensions_names=["water"])

In [22]:
accounts.extensions

{'water': <matmat.core.accounts.extension.core.Extension at 0x1c3d07a4dd0>}

In [ ]:
accounts.add_extension(ghg_emissions)

In [ ]:
accounts.extensions

## Update a data

In [19]:
accounts.water.F_x_dom.df

AttributeError: 'Accounts' object has no attribute 'water'

In [ ]:
accounts.water.F_x_dom.set_value_at(
    rows_filters={"perimeter": ["other"]}, 
    columns_filters={"sector": ["Livestock", "Crops"]}, 
    value=1000.0
)

In [24]:
df = accounts_3_9.water.F_x_dom.df

In [29]:
accounts_3_10.water.F_x_dom.df

region                                                     AT            \
sector                                             Paddy rice     Wheat
indicator
Water Consumption Blue - Agriculture - rice               0.0  0.000000
Water Consumption Blue - Agriculture - wheat              0.0  0.003337
Water Consumption Blue - Agriculture - other ce...        0.0  0.000000
Water Consumption Blue - Agriculture - roots an...        0.0  0.000000
Water Consumption Blue - Agriculture - sugar crops        0.0  0.000000
...                                                       ...       ...
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Domestic - domestic Wa...        0.0  0.000000

region                                                                \
sector                                             Cereal grains nec
indicator
Water Consumption Blue - Agriculture - rice                 0.000000
Water Consumption Blue - Agriculture - wheat                0.000000
Water Consumption Blue - Agriculture - other ce...          7.523106
Water Consumption Blue - Agriculture - roots an...          0.000000
Water Consumption Blue - Agriculture - sugar crops          0.000000
...                                                              ...
Water Consumption Blue - Electricity - once-thr...          0.000000
Water Consumption Blue - Electricity - once-thr...          0.000000
Water Consumption Blue - Electricity - once-thr...          0.000000
Water Consumption Blue - Electricity - once-thr...          0.000000
Water Consumption Blue - Domestic - domestic Wa...          0.000000

region                                                                      \
sector                                             Vegetables, fruit, nuts
indicator
Water Consumption Blue - Agriculture - rice                            0.0
Water Consumption Blue - Agriculture - wheat                           0.0
Water Consumption Blue - Agriculture - other ce...                     0.0
Water Consumption Blue - Agriculture - roots an...                     0.0
Water Consumption Blue - Agriculture - sugar crops                     0.0
...                                                                    ...
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Domestic - domestic Wa...                     0.0

region                                                        \
sector                                             Oil seeds
indicator
Water Consumption Blue - Agriculture - rice              0.0
Water Consumption Blue - Agriculture - wheat             0.0
Water Consumption Blue - Agriculture - other ce...       0.0
Water Consumption Blue - Agriculture - roots an...       0.0
Water Consumption Blue - Agriculture - sugar crops       0.0
...                                                      ...
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Domestic - domestic Wa...       0.0

region                                                                     \
sector                                             Sugar cane, sugar beet
indicator
Water Consumption Blue - Agriculture - rice                      0.000000
Water Consumption Blue - Agriculture - wheat                     0.000000
Water Consumption Blue - Agriculture - other ce...               0.000000
Water Consumption Blue - Agriculture - roots an...               0.000000
Water Consumption Blue - Agriculture - sugar crops              15.365852
...                                                                   ...
Water Consumption Blue - Electricity - once-thr...               0.000000
Water Consumption Blue - Electricity - once-thr...               0.000000
Water Consumption Blue - Electricity - once-thr...               0.000000
Water Consumption Blue - Electricity - once-thr...               0.000000
Water Consumption Blue - Domestic - domestic Wa...               0.000000

region                                                                 \
sector                                             Plant-based fibers
indicator
Water Consumption Blue - Agriculture - rice                       0.0
Water Consumption Blue - Agriculture - wheat                      0.0
Water Consumption Blue - Agriculture - other ce...                0.0
Water Consumption Blue - Agriculture - roots an...                0.0
Water Consumption Blue - Agriculture - sugar crops                0.0
...                                                               ...
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Domestic - domestic Wa...                0.0

region                                                                     \
sector                                              Crops nec Cattle Pigs
indicator
Water Consumption Blue - Agriculture - rice          0.000000    0.0  0.0
Water Consumption Blue - Agriculture - wheat         0.000000    0.0  0.0
Water Consumption Blue - Agriculture - other ce...   0.000000    0.0  0.0
Water Consumption Blue - Agriculture - roots an...  21.509556    0.0  0.0
Water Consumption Blue - Agriculture - sugar crops   0.000000    0.0  0.0
...                                                       ...    ...  ...
Water Consumption Blue - Electricity - once-thr...   0.000000    0.0  0.0
Water Consumption Blue - Electricity - once-thr...   0.000000    0.0  0.0
Water Consumption Blue - Electricity - once-thr...   0.000000    0.0  0.0
Water Consumption Blue - Electricity - once-thr...   0.000000    0.0  0.0
Water Consumption Blue - Domestic - domestic Wa...   0.000000    0.0  0.0

region                                              ...  \
sector                                              ...
indicator                                           ...
Water Consumption Blue - Agriculture - rice         ...
Water Consumption Blue - Agriculture - wheat        ...
Water Consumption Blue - Agriculture - other ce...  ...
Water Consumption Blue - Agriculture - roots an...  ...
Water Consumption Blue - Agriculture - sugar crops  ...
...                                                 ...
Water Consumption Blue - Electricity - once-thr...  ...
Water Consumption Blue - Electricity - once-thr...  ...
Water Consumption Blue - Electricity - once-thr...  ...
Water Consumption Blue - Electricity - once-thr...  ...
Water Consumption Blue - Domestic - domestic Wa...  ...

region                                                                        WM  \
sector                                             Paper for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                  0.0
Water Consumption Blue - Agriculture - wheat                                 0.0
Water Consumption Blue - Agriculture - other ce...                           0.0
Water Consumption Blue - Agriculture - roots an...                           0.0
Water Consumption Blue - Agriculture - sugar crops                           0.0
...                                                                          ...
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Domestic - domestic Wa...                           0.0

region                                                                                    \
sector                                             Plastic waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                          0.0
Water Consumption Blue - Agriculture - wheat                                         0.0
Water Consumption Blue - Agriculture - other ce...                                   0.0
Water Consumption Blue - Agriculture - roots an...                                   0.0
Water Consumption Blue - Agriculture - sugar crops                                   0.0
...                                                                                  ...
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Domestic - domestic Wa...                                   0.0

region                                                                                                  \
sector                                             Inert/metal/hazardous waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                                       0.0
Water Consumption Blue - Agriculture - wheat                                                      0.0
Water Consumption Blue - Agriculture - other ce...                                                0.0
Water Consumption Blue - Agriculture - roots an...                                                0.0
Water Consumption Blue - Agriculture - sugar crops                                                0.0
...                                                                                               ...
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Domestic - domestic Wa...                                                0.0

region                                                                                     \
sector                                             Textiles waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                           0.0
Water Consumption Blue - Agriculture - wheat                                          0.0
Water Consumption Blue - Agriculture - other ce...                                    0.0
Water Consumption Blue - Agriculture - roots an...                                    0.0
Water Consumption Blue - Agriculture - sugar crops                                    0.0
...                                                                                   ...
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Domestic - domestic Wa...                                    0.0

region                                                                                 \
sector                                             Wood waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                       0.0
Water Consumption Blue - Agriculture - wheat                                      0.0
Water Consumption Blue - Agriculture - other ce...                                0.0
Water Consumption Blue - Agriculture - roots an...                                0.0
Water Consumption Blue - Agriculture - sugar crops                                0.0
...                                                                               ...
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Domestic - domestic Wa...                                0.0

region                                                                                           \
sector                                             Membership organisation services n.e.c. (91)
indicator
Water Consumption Blue - Agriculture - rice                                                 0.0
Water Consumption Blue - Agriculture - wheat                                                0.0
Water Consumption Blue - Agriculture - other ce...                                          0.0
Water Consumption Blue - Agriculture - roots an...                                          0.0
Water Consumption Blue - Agriculture - sugar crops                                          0.0
...                                                                                         ...
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Domestic - domestic Wa...                                          0.0

region                                                                                                \
sector                                             Recreational, cultural and sporting services (92)
indicator
Water Consumption Blue - Agriculture - rice                                                      0.0
Water Consumption Blue - Agriculture - wheat                                                     0.0
Water Consumption Blue - Agriculture - other ce...                                               0.0
Water Consumption Blue - Agriculture - roots an...                                               0.0
Water Consumption Blue - Agriculture - sugar crops                                               0.0
...                                                                                              ...
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Domestic - domestic Wa...                                               0.0

region                                                                  \
sector                                             Other services (93)
indicator
Water Consumption Blue - Agriculture - rice                        0.0
Water Consumption Blue - Agriculture - wheat                       0.0
Water Consumption Blue - Agriculture - other ce...                 0.0
Water Consumption Blue - Agriculture - roots an...                 0.0
Water Consumption Blue - Agriculture - sugar crops                 0.0
...                                                                ...
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Domestic - domestic Wa...                 0.0

region                                                                                            \
sector                                             Private households with employed persons (95)
indicator
Water Consumption Blue - Agriculture - rice                                                  0.0
Water Consumption Blue - Agriculture - wheat                                                 0.0
Water Consumption Blue - Agriculture - other ce...                                           0.0
Water Consumption Blue - Agriculture - roots an...                                           0.0
Water Consumption Blue - Agriculture - sugar crops                                           0.0
...                                                                                          ...
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Domestic - domestic Wa...                                           0.0

region
sector                                             Extra-territorial organizations and bodies
indicator
Water Consumption Blue - Agriculture - rice                                               0.0
Water Consumption Blue - Agriculture - wheat                                              0.0
Water Consumption Blue - Agriculture - other ce...                                        0.0
Water Consumption Blue - Agriculture - roots an...                                        0.0
Water Consumption Blue - Agriculture - sugar crops                                        0.0
...                                                                                       ...
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Domestic - domestic Wa...                                        0.0

[103 rows x 9800 columns]

In [31]:
accounts_3_10.water.F_x_dom.set_values(df.values)

In [32]:
accounts_3_10.water.F_x_dom.df

region                                                     AT            \
sector                                             Paddy rice     Wheat
indicator
Water Consumption Blue - Agriculture - rice               0.0  0.000000
Water Consumption Blue - Agriculture - wheat              0.0  0.002001
Water Consumption Blue - Agriculture - other ce...        0.0  0.000000
Water Consumption Blue - Agriculture - roots an...        0.0  0.000000
Water Consumption Blue - Agriculture - sugar crops        0.0  0.000000
...                                                       ...       ...
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Electricity - once-thr...        0.0  0.000000
Water Consumption Blue - Domestic - domestic Wa...        0.0  0.000000

region                                                                \
sector                                             Cereal grains nec
indicator
Water Consumption Blue - Agriculture - rice                  0.00000
Water Consumption Blue - Agriculture - wheat                 0.00000
Water Consumption Blue - Agriculture - other ce...           6.03856
Water Consumption Blue - Agriculture - roots an...           0.00000
Water Consumption Blue - Agriculture - sugar crops           0.00000
...                                                              ...
Water Consumption Blue - Electricity - once-thr...           0.00000
Water Consumption Blue - Electricity - once-thr...           0.00000
Water Consumption Blue - Electricity - once-thr...           0.00000
Water Consumption Blue - Electricity - once-thr...           0.00000
Water Consumption Blue - Domestic - domestic Wa...           0.00000

region                                                                      \
sector                                             Vegetables, fruit, nuts
indicator
Water Consumption Blue - Agriculture - rice                            0.0
Water Consumption Blue - Agriculture - wheat                           0.0
Water Consumption Blue - Agriculture - other ce...                     0.0
Water Consumption Blue - Agriculture - roots an...                     0.0
Water Consumption Blue - Agriculture - sugar crops                     0.0
...                                                                    ...
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Electricity - once-thr...                     0.0
Water Consumption Blue - Domestic - domestic Wa...                     0.0

region                                                        \
sector                                             Oil seeds
indicator
Water Consumption Blue - Agriculture - rice              0.0
Water Consumption Blue - Agriculture - wheat             0.0
Water Consumption Blue - Agriculture - other ce...       0.0
Water Consumption Blue - Agriculture - roots an...       0.0
Water Consumption Blue - Agriculture - sugar crops       0.0
...                                                      ...
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Electricity - once-thr...       0.0
Water Consumption Blue - Domestic - domestic Wa...       0.0

region                                                                     \
sector                                             Sugar cane, sugar beet
indicator
Water Consumption Blue - Agriculture - rice                        0.0000
Water Consumption Blue - Agriculture - wheat                       0.0000
Water Consumption Blue - Agriculture - other ce...                 0.0000
Water Consumption Blue - Agriculture - roots an...                 0.0000
Water Consumption Blue - Agriculture - sugar crops                19.4731
...                                                                   ...
Water Consumption Blue - Electricity - once-thr...                 0.0000
Water Consumption Blue - Electricity - once-thr...                 0.0000
Water Consumption Blue - Electricity - once-thr...                 0.0000
Water Consumption Blue - Electricity - once-thr...                 0.0000
Water Consumption Blue - Domestic - domestic Wa...                 0.0000

region                                                                 \
sector                                             Plant-based fibers
indicator
Water Consumption Blue - Agriculture - rice                       0.0
Water Consumption Blue - Agriculture - wheat                      0.0
Water Consumption Blue - Agriculture - other ce...                0.0
Water Consumption Blue - Agriculture - roots an...                0.0
Water Consumption Blue - Agriculture - sugar crops                0.0
...                                                               ...
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Electricity - once-thr...                0.0
Water Consumption Blue - Domestic - domestic Wa...                0.0

region                                                                    ...  \
sector                                             Crops nec Cattle Pigs  ...
indicator                                                                 ...
Water Consumption Blue - Agriculture - rice            0.000    0.0  0.0  ...
Water Consumption Blue - Agriculture - wheat           0.000    0.0  0.0  ...
Water Consumption Blue - Agriculture - other ce...     0.000    0.0  0.0  ...
Water Consumption Blue - Agriculture - roots an...    17.265    0.0  0.0  ...
Water Consumption Blue - Agriculture - sugar crops     0.000    0.0  0.0  ...
...                                                      ...    ...  ...  ...
Water Consumption Blue - Electricity - once-thr...     0.000    0.0  0.0  ...
Water Consumption Blue - Electricity - once-thr...     0.000    0.0  0.0  ...
Water Consumption Blue - Electricity - once-thr...     0.000    0.0  0.0  ...
Water Consumption Blue - Electricity - once-thr...     0.000    0.0  0.0  ...
Water Consumption Blue - Domestic - domestic Wa...     0.000    0.0  0.0  ...

region                                                                        WM  \
sector                                             Paper for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                  0.0
Water Consumption Blue - Agriculture - wheat                                 0.0
Water Consumption Blue - Agriculture - other ce...                           0.0
Water Consumption Blue - Agriculture - roots an...                           0.0
Water Consumption Blue - Agriculture - sugar crops                           0.0
...                                                                          ...
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Electricity - once-thr...                           0.0
Water Consumption Blue - Domestic - domestic Wa...                           0.0

region                                                                                    \
sector                                             Plastic waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                          0.0
Water Consumption Blue - Agriculture - wheat                                         0.0
Water Consumption Blue - Agriculture - other ce...                                   0.0
Water Consumption Blue - Agriculture - roots an...                                   0.0
Water Consumption Blue - Agriculture - sugar crops                                   0.0
...                                                                                  ...
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Electricity - once-thr...                                   0.0
Water Consumption Blue - Domestic - domestic Wa...                                   0.0

region                                                                                                  \
sector                                             Inert/metal/hazardous waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                                       0.0
Water Consumption Blue - Agriculture - wheat                                                      0.0
Water Consumption Blue - Agriculture - other ce...                                                0.0
Water Consumption Blue - Agriculture - roots an...                                                0.0
Water Consumption Blue - Agriculture - sugar crops                                                0.0
...                                                                                               ...
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Electricity - once-thr...                                                0.0
Water Consumption Blue - Domestic - domestic Wa...                                                0.0

region                                                                                     \
sector                                             Textiles waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                           0.0
Water Consumption Blue - Agriculture - wheat                                          0.0
Water Consumption Blue - Agriculture - other ce...                                    0.0
Water Consumption Blue - Agriculture - roots an...                                    0.0
Water Consumption Blue - Agriculture - sugar crops                                    0.0
...                                                                                   ...
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Electricity - once-thr...                                    0.0
Water Consumption Blue - Domestic - domestic Wa...                                    0.0

region                                                                                 \
sector                                             Wood waste for treatment: landfill
indicator
Water Consumption Blue - Agriculture - rice                                       0.0
Water Consumption Blue - Agriculture - wheat                                      0.0
Water Consumption Blue - Agriculture - other ce...                                0.0
Water Consumption Blue - Agriculture - roots an...                                0.0
Water Consumption Blue - Agriculture - sugar crops                                0.0
...                                                                               ...
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Electricity - once-thr...                                0.0
Water Consumption Blue - Domestic - domestic Wa...                                0.0

region                                                                                           \
sector                                             Membership organisation services n.e.c. (91)
indicator
Water Consumption Blue - Agriculture - rice                                                 0.0
Water Consumption Blue - Agriculture - wheat                                                0.0
Water Consumption Blue - Agriculture - other ce...                                          0.0
Water Consumption Blue - Agriculture - roots an...                                          0.0
Water Consumption Blue - Agriculture - sugar crops                                          0.0
...                                                                                         ...
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Electricity - once-thr...                                          0.0
Water Consumption Blue - Domestic - domestic Wa...                                          0.0

region                                                                                                \
sector                                             Recreational, cultural and sporting services (92)
indicator
Water Consumption Blue - Agriculture - rice                                                      0.0
Water Consumption Blue - Agriculture - wheat                                                     0.0
Water Consumption Blue - Agriculture - other ce...                                               0.0
Water Consumption Blue - Agriculture - roots an...                                               0.0
Water Consumption Blue - Agriculture - sugar crops                                               0.0
...                                                                                              ...
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Electricity - once-thr...                                               0.0
Water Consumption Blue - Domestic - domestic Wa...                                               0.0

region                                                                  \
sector                                             Other services (93)
indicator
Water Consumption Blue - Agriculture - rice                        0.0
Water Consumption Blue - Agriculture - wheat                       0.0
Water Consumption Blue - Agriculture - other ce...                 0.0
Water Consumption Blue - Agriculture - roots an...                 0.0
Water Consumption Blue - Agriculture - sugar crops                 0.0
...                                                                ...
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Electricity - once-thr...                 0.0
Water Consumption Blue - Domestic - domestic Wa...                 0.0

region                                                                                            \
sector                                             Private households with employed persons (95)
indicator
Water Consumption Blue - Agriculture - rice                                                  0.0
Water Consumption Blue - Agriculture - wheat                                                 0.0
Water Consumption Blue - Agriculture - other ce...                                           0.0
Water Consumption Blue - Agriculture - roots an...                                           0.0
Water Consumption Blue - Agriculture - sugar crops                                           0.0
...                                                                                          ...
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Electricity - once-thr...                                           0.0
Water Consumption Blue - Domestic - domestic Wa...                                           0.0

region
sector                                             Extra-territorial organizations and bodies
indicator
Water Consumption Blue - Agriculture - rice                                               0.0
Water Consumption Blue - Agriculture - wheat                                              0.0
Water Consumption Blue - Agriculture - other ce...                                        0.0
Water Consumption Blue - Agriculture - roots an...                                        0.0
Water Consumption Blue - Agriculture - sugar crops                                        0.0
...                                                                                       ...
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Electricity - once-thr...                                        0.0
Water Consumption Blue - Domestic - domestic Wa...                                        0.0

[103 rows x 9800 columns]

In [ ]:
accounts.ghg_emissions.F_x_dom.reset()

In [ ]:
accounts.ghg_emissions.F_x_dom.clean_residual_nan()

## Save accounts to path

In [ ]:
accounts.save_to_path("./accounts_saved", export_format=["pickle"])